// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
    excerpt_block: () => import(/* webpackChunkName: "prismic__slices__excerpt_block" */ './ExcerptBlock/index.vue'),
    gallery_block: () => import(/* webpackChunkName: "prismic__slices__gallery_block" */ './GalleryBlock/index.vue'),
    introduction_block: () =>
        import(/* webpackChunkName: "prismic__slices__introduction_block" */ './IntroductionBlock/index.vue'),
    partners_block: () => import(/* webpackChunkName: "prismic__slices__partners_block" */ './PartnersBlock/index.vue'),
    project_listing_block: () =>
        import(/* webpackChunkName: "prismic__slices__project_listing_block" */ './ProjectListingBlock/index.vue'),
    project_push_block: () =>
        import(/* webpackChunkName: "prismic__slices__project_push_block" */ './ProjectPushBlock/index.vue'),
    promote_block: () => import(/* webpackChunkName: "prismic__slices__promote_block" */ './PromoteBlock/index.vue'),
    skills_block: () => import(/* webpackChunkName: "prismic__slices__skills_block" */ './SkillsBlock/index.vue'),
}
