// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
    introduction_block: () =>
        import(/* webpackChunkName: "prismic__slices__introduction_block" */ './IntroductionBlock/index.vue'),
    project_listing_block: () =>
        import(/* webpackChunkName: "prismic__slices__project_listing_block" */ './ProjectListingBlock/index.vue'),
    project_push_block: () =>
        import(/* webpackChunkName: "prismic__slices__project_push_block" */ './ProjectPushBlock/index.vue'),
}
